### ISSUE TITLE
Center Spinner component within content areas

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/SWoT#159]
Presently the custom Spinner control is centered vertically within parent containers, including titlebars and headers.  Review implementation and center the Spinner by applying the following CSS:

```css
{
    top: 'initial',
    bottom: 'initial',
}
```
